name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version: 1.26.4

      - name: Go version
        run: go version

      - name: Run tests
        run: go test ./...

      - name: Run vulnerability scan
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...
